# Generated by Django 5.1.6 on 2025-02-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_shieldmodel_max_ballistic_absorption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmodel',
            name='shield_faces',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Bubble'), (2, 'FrontBack'), (4, 'Quadrant')]),
        ),
    ]
