# Generated by Django 5.1.6 on 2025-02-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_loadoutmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shieldmodel',
            name='raw_data',
            field=models.JSONField(null=True),
        ),
    ]
