# Generated by Django 5.1.6 on 2025-02-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_shieldmodel_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadoutmodel',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='loadoutmodel',
            name='raw_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='loadoutmodel',
            name='shields',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='loadoutmodel',
            name='shields_power_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='loadoutmodel',
            name='ship_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='loadoutmodel',
            name='weapons',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='loadoutmodel',
            name='weapons_power_percentage',
            field=models.FloatField(null=True),
        ),
    ]
