# Generated by Django 5.1.6 on 2025-02-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_loadoutmodel_name_alter_loadoutmodel_raw_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weaponmodel',
            old_name='accuracy',
            new_name='spread',
        ),
        migrations.AddField(
            model_name='shipmodel',
            name='scm_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shipmodel',
            name='total_hp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shipmodel',
            name='visible_hull_area',
            field=models.FloatField(null=True),
        ),
    ]
